oref:
  url: "https://www.oref.org.il/WarningMessages/alert/alerts.json"
  poll_interval_sec: 1
  timeout_sec: 2

match:
  cities:
    - "תל אביב - מרכז"

wled:
  base_url: "http://192.168.1.195/"
  #path_pre_alert: "/win&T=2&PL=1"
  #path_alert: "/win&T=2&PL=2"
  path_end: "/win&PL=3"
  post_delay_sec: 60
  post_delay_path: "/win&PL=2"

runtime:
  dry_run: false